<?php

namespace ContainerKfD6xvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UQ2dMonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uQ2dMon' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uQ2dMon'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hr' => ['privates', 'App\\Repository\\HomeRepository', 'getHomeRepositoryService', true],
            'lr' => ['privates', 'App\\Repository\\LiteratureRepository', 'getLiteratureRepositoryService', true],
            'qr' => ['privates', 'App\\Repository\\QuotesRepository', 'getQuotesRepositoryService', true],
            'sr' => ['privates', 'App\\Repository\\SeancesRepository', 'getSeancesRepositoryService', true],
        ], [
            'hr' => 'App\\Repository\\HomeRepository',
            'lr' => 'App\\Repository\\LiteratureRepository',
            'qr' => 'App\\Repository\\QuotesRepository',
            'sr' => 'App\\Repository\\SeancesRepository',
        ]);
    }
}
