<?php

namespace ContainerKfD6xvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WYm0bSHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WYm0bSH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WYm0bSH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hr' => ['privates', 'App\\Repository\\HomeRepository', 'getHomeRepositoryService', true],
        ], [
            'hr' => 'App\\Repository\\HomeRepository',
        ]);
    }
}
