<?php

namespace ContainerKfD6xvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SX4EdV9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sX4EdV9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sX4EdV9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'qr' => ['privates', 'App\\Repository\\QuotesRepository', 'getQuotesRepositoryService', true],
        ], [
            'qr' => 'App\\Repository\\QuotesRepository',
        ]);
    }
}
