<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home_page_browse' => [[], ['_controller' => 'App\\Controller\\Admin\\HomeController::index'], [], [['text', '/accueil-page']], [], [], []],
    'home_page_edit' => [[], ['_controller' => 'App\\Controller\\Admin\\HomeController::edit'], [], [['text', '/accueil-page/edit']], [], [], []],
    'literature_browse' => [[], ['_controller' => 'App\\Controller\\Admin\\LiteratureController::index'], [], [['text', '/litterature']], [], [], []],
    'literature_read' => [['id'], ['_controller' => 'App\\Controller\\Admin\\LiteratureController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/litterature/read']], [], [], []],
    'literature_display' => [['id'], ['_controller' => 'App\\Controller\\Admin\\LiteratureController::displayOnWebsite'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/litterature/display']], [], [], []],
    'literature_add' => [[], ['_controller' => 'App\\Controller\\Admin\\LiteratureController::add'], [], [['text', '/litterature/add']], [], [], []],
    'literature_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\LiteratureController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/litterature/edit']], [], [], []],
    'literature_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\LiteratureController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/litterature/delete']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\Admin\\MainController::index'], [], [['text', '/']], [], [], []],
    'quotes_browse' => [[], ['_controller' => 'App\\Controller\\Admin\\QuotesController::index'], [], [['text', '/citations']], [], [], []],
    'quotes_read' => [['id'], ['_controller' => 'App\\Controller\\Admin\\QuotesController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/citations/read']], [], [], []],
    'quotes_display' => [['id'], ['_controller' => 'App\\Controller\\Admin\\QuotesController::displayOnWebsite'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/citations/display']], [], [], []],
    'quotes_add' => [[], ['_controller' => 'App\\Controller\\Admin\\QuotesController::add'], [], [['text', '/citations/add']], [], [], []],
    'quotes_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\QuotesController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/citations/edit']], [], [], []],
    'quotes_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\QuotesController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/citations/delete']], [], [], []],
    'seances_browse' => [[], ['_controller' => 'App\\Controller\\Admin\\SeancesController::index'], [], [['text', '/seances']], [], [], []],
    'seances_display' => [['id'], ['_controller' => 'App\\Controller\\Admin\\SeancesController::displayOnWebsite'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/seances/display']], [], [], []],
    'seances_add' => [[], ['_controller' => 'App\\Controller\\Admin\\SeancesController::add'], [], [['text', '/seances/add']], [], [], []],
    'seances_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\SeancesController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/seances/edit']], [], [], []],
    'seances_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\SeancesController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/seances/delete']], [], [], []],
    'api_all' => [[], ['_controller' => 'App\\Controller\\Api\\MainController::apiAll'], [], [['text', '/api/all']], [], [], []],
];
