<?php

namespace Container20u2Ire;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZvkx4PService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gZvkx4P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gZvkx4P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'lr' => ['privates', 'App\\Repository\\LiteratureRepository', 'getLiteratureRepositoryService', true],
        ], [
            'em' => '?',
            'lr' => 'App\\Repository\\LiteratureRepository',
        ]);
    }
}
