<?php

namespace Container20u2Ire;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9HHMG67Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9HHMG67' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9HHMG67'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lr' => ['privates', 'App\\Repository\\LiteratureRepository', 'getLiteratureRepositoryService', true],
        ], [
            'lr' => 'App\\Repository\\LiteratureRepository',
        ]);
    }
}
