<?php

namespace Container20u2Ire;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\HomeController::edit' => ['privates', '.service_locator.qr4n8P8', 'get_ServiceLocator_Qr4n8P8Service', true],
            'App\\Controller\\Admin\\HomeController::index' => ['privates', '.service_locator.WYm0bSH', 'get_ServiceLocator_WYm0bSHService', true],
            'App\\Controller\\Admin\\LiteratureController::add' => ['privates', '.service_locator.vtx39BU', 'get_ServiceLocator_Vtx39BUService', true],
            'App\\Controller\\Admin\\LiteratureController::delete' => ['privates', '.service_locator.gZvkx4P', 'get_ServiceLocator_GZvkx4PService', true],
            'App\\Controller\\Admin\\LiteratureController::displayOnWebsite' => ['privates', '.service_locator.gZvkx4P', 'get_ServiceLocator_GZvkx4PService', true],
            'App\\Controller\\Admin\\LiteratureController::edit' => ['privates', '.service_locator.4UnonHg', 'get_ServiceLocator_4UnonHgService', true],
            'App\\Controller\\Admin\\LiteratureController::index' => ['privates', '.service_locator.9HHMG67', 'get_ServiceLocator_9HHMG67Service', true],
            'App\\Controller\\Admin\\LiteratureController::read' => ['privates', '.service_locator.9HHMG67', 'get_ServiceLocator_9HHMG67Service', true],
            'App\\Controller\\Admin\\QuotesController::add' => ['privates', '.service_locator.vtx39BU', 'get_ServiceLocator_Vtx39BUService', true],
            'App\\Controller\\Admin\\QuotesController::delete' => ['privates', '.service_locator.sWK_LuZ', 'get_ServiceLocator_SWKLuZService', true],
            'App\\Controller\\Admin\\QuotesController::displayOnWebsite' => ['privates', '.service_locator.sWK_LuZ', 'get_ServiceLocator_SWKLuZService', true],
            'App\\Controller\\Admin\\QuotesController::edit' => ['privates', '.service_locator.ytbdr1U', 'get_ServiceLocator_Ytbdr1UService', true],
            'App\\Controller\\Admin\\QuotesController::index' => ['privates', '.service_locator.sX4EdV9', 'get_ServiceLocator_SX4EdV9Service', true],
            'App\\Controller\\Admin\\QuotesController::read' => ['privates', '.service_locator.sX4EdV9', 'get_ServiceLocator_SX4EdV9Service', true],
            'App\\Controller\\Admin\\SeancesController::add' => ['privates', '.service_locator.kQqLpU0', 'get_ServiceLocator_KQqLpU0Service', true],
            'App\\Controller\\Admin\\SeancesController::delete' => ['privates', '.service_locator.b.iwPJb', 'get_ServiceLocator_B_IwPJbService', true],
            'App\\Controller\\Admin\\SeancesController::displayOnWebsite' => ['privates', '.service_locator.b.iwPJb', 'get_ServiceLocator_B_IwPJbService', true],
            'App\\Controller\\Admin\\SeancesController::edit' => ['privates', '.service_locator.kQqLpU0', 'get_ServiceLocator_KQqLpU0Service', true],
            'App\\Controller\\Admin\\SeancesController::index' => ['privates', '.service_locator.vD1FTq9', 'get_ServiceLocator_VD1FTq9Service', true],
            'App\\Controller\\Api\\MainController::apiAll' => ['privates', '.service_locator.uQ2dMon', 'get_ServiceLocator_UQ2dMonService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\HomeController:edit' => ['privates', '.service_locator.qr4n8P8', 'get_ServiceLocator_Qr4n8P8Service', true],
            'App\\Controller\\Admin\\HomeController:index' => ['privates', '.service_locator.WYm0bSH', 'get_ServiceLocator_WYm0bSHService', true],
            'App\\Controller\\Admin\\LiteratureController:add' => ['privates', '.service_locator.vtx39BU', 'get_ServiceLocator_Vtx39BUService', true],
            'App\\Controller\\Admin\\LiteratureController:delete' => ['privates', '.service_locator.gZvkx4P', 'get_ServiceLocator_GZvkx4PService', true],
            'App\\Controller\\Admin\\LiteratureController:displayOnWebsite' => ['privates', '.service_locator.gZvkx4P', 'get_ServiceLocator_GZvkx4PService', true],
            'App\\Controller\\Admin\\LiteratureController:edit' => ['privates', '.service_locator.4UnonHg', 'get_ServiceLocator_4UnonHgService', true],
            'App\\Controller\\Admin\\LiteratureController:index' => ['privates', '.service_locator.9HHMG67', 'get_ServiceLocator_9HHMG67Service', true],
            'App\\Controller\\Admin\\LiteratureController:read' => ['privates', '.service_locator.9HHMG67', 'get_ServiceLocator_9HHMG67Service', true],
            'App\\Controller\\Admin\\QuotesController:add' => ['privates', '.service_locator.vtx39BU', 'get_ServiceLocator_Vtx39BUService', true],
            'App\\Controller\\Admin\\QuotesController:delete' => ['privates', '.service_locator.sWK_LuZ', 'get_ServiceLocator_SWKLuZService', true],
            'App\\Controller\\Admin\\QuotesController:displayOnWebsite' => ['privates', '.service_locator.sWK_LuZ', 'get_ServiceLocator_SWKLuZService', true],
            'App\\Controller\\Admin\\QuotesController:edit' => ['privates', '.service_locator.ytbdr1U', 'get_ServiceLocator_Ytbdr1UService', true],
            'App\\Controller\\Admin\\QuotesController:index' => ['privates', '.service_locator.sX4EdV9', 'get_ServiceLocator_SX4EdV9Service', true],
            'App\\Controller\\Admin\\QuotesController:read' => ['privates', '.service_locator.sX4EdV9', 'get_ServiceLocator_SX4EdV9Service', true],
            'App\\Controller\\Admin\\SeancesController:add' => ['privates', '.service_locator.kQqLpU0', 'get_ServiceLocator_KQqLpU0Service', true],
            'App\\Controller\\Admin\\SeancesController:delete' => ['privates', '.service_locator.b.iwPJb', 'get_ServiceLocator_B_IwPJbService', true],
            'App\\Controller\\Admin\\SeancesController:displayOnWebsite' => ['privates', '.service_locator.b.iwPJb', 'get_ServiceLocator_B_IwPJbService', true],
            'App\\Controller\\Admin\\SeancesController:edit' => ['privates', '.service_locator.kQqLpU0', 'get_ServiceLocator_KQqLpU0Service', true],
            'App\\Controller\\Admin\\SeancesController:index' => ['privates', '.service_locator.vD1FTq9', 'get_ServiceLocator_VD1FTq9Service', true],
            'App\\Controller\\Api\\MainController:apiAll' => ['privates', '.service_locator.uQ2dMon', 'get_ServiceLocator_UQ2dMonService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\HomeController::edit' => '?',
            'App\\Controller\\Admin\\HomeController::index' => '?',
            'App\\Controller\\Admin\\LiteratureController::add' => '?',
            'App\\Controller\\Admin\\LiteratureController::delete' => '?',
            'App\\Controller\\Admin\\LiteratureController::displayOnWebsite' => '?',
            'App\\Controller\\Admin\\LiteratureController::edit' => '?',
            'App\\Controller\\Admin\\LiteratureController::index' => '?',
            'App\\Controller\\Admin\\LiteratureController::read' => '?',
            'App\\Controller\\Admin\\QuotesController::add' => '?',
            'App\\Controller\\Admin\\QuotesController::delete' => '?',
            'App\\Controller\\Admin\\QuotesController::displayOnWebsite' => '?',
            'App\\Controller\\Admin\\QuotesController::edit' => '?',
            'App\\Controller\\Admin\\QuotesController::index' => '?',
            'App\\Controller\\Admin\\QuotesController::read' => '?',
            'App\\Controller\\Admin\\SeancesController::add' => '?',
            'App\\Controller\\Admin\\SeancesController::delete' => '?',
            'App\\Controller\\Admin\\SeancesController::displayOnWebsite' => '?',
            'App\\Controller\\Admin\\SeancesController::edit' => '?',
            'App\\Controller\\Admin\\SeancesController::index' => '?',
            'App\\Controller\\Api\\MainController::apiAll' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\HomeController:edit' => '?',
            'App\\Controller\\Admin\\HomeController:index' => '?',
            'App\\Controller\\Admin\\LiteratureController:add' => '?',
            'App\\Controller\\Admin\\LiteratureController:delete' => '?',
            'App\\Controller\\Admin\\LiteratureController:displayOnWebsite' => '?',
            'App\\Controller\\Admin\\LiteratureController:edit' => '?',
            'App\\Controller\\Admin\\LiteratureController:index' => '?',
            'App\\Controller\\Admin\\LiteratureController:read' => '?',
            'App\\Controller\\Admin\\QuotesController:add' => '?',
            'App\\Controller\\Admin\\QuotesController:delete' => '?',
            'App\\Controller\\Admin\\QuotesController:displayOnWebsite' => '?',
            'App\\Controller\\Admin\\QuotesController:edit' => '?',
            'App\\Controller\\Admin\\QuotesController:index' => '?',
            'App\\Controller\\Admin\\QuotesController:read' => '?',
            'App\\Controller\\Admin\\SeancesController:add' => '?',
            'App\\Controller\\Admin\\SeancesController:delete' => '?',
            'App\\Controller\\Admin\\SeancesController:displayOnWebsite' => '?',
            'App\\Controller\\Admin\\SeancesController:edit' => '?',
            'App\\Controller\\Admin\\SeancesController:index' => '?',
            'App\\Controller\\Api\\MainController:apiAll' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
