<?php

namespace Container20u2Ire;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiteratureControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\LiteratureController' shared autowired service.
     *
     * @return \App\Controller\Admin\LiteratureController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\LiteratureController'] = $instance = new \App\Controller\Admin\LiteratureController();

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\Admin\\LiteratureController', $container));

        return $instance;
    }
}
