<?php

namespace Container20u2Ire;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeancesTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SeancesType' shared autowired service.
     *
     * @return \App\Form\SeancesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SeancesType'] = new \App\Form\SeancesType();
    }
}
