<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Seances extends \App\Entity\Seances implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'content', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'duration', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'population', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'displayOnWebsite', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'displayable'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'content', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'duration', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'population', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'displayOnWebsite', '' . "\0" . 'App\\Entity\\Seances' . "\0" . 'displayable'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Seances $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent(string $content): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration(int $duration): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$duration]);

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(int $price): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtValue', []);

        return parent::setUpdatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getPopulation(): ?\App\Entity\Population
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPopulation', []);

        return parent::getPopulation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPopulation(?\App\Entity\Population $population): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPopulation', [$population]);

        return parent::setPopulation($population);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayOnWebsite(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayOnWebsite', []);

        return parent::getDisplayOnWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayOnWebsite(bool $displayOnWebsite): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayOnWebsite', [$displayOnWebsite]);

        return parent::setDisplayOnWebsite($displayOnWebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayable', []);

        return parent::getDisplayable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayable(bool $displayable): \App\Entity\Seances
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayable', [$displayable]);

        return parent::setDisplayable($displayable);
    }

}
